"""Heredity-aware interaction frontier construction."""

from __future__ import annotations

from itertools import combinations
from typing import Iterable, Sequence

from .contracts import Interaction


def immediate_subsets(interaction: Sequence[str]) -> tuple[Interaction, ...]:
    """Return every subset containing exactly one fewer feature."""
    term = tuple(interaction)
    if len(term) < 2:
        return ()
    return tuple(term[:index] + term[index + 1 :] for index in range(len(term)))


def interaction_frontier(
    feature_names: Sequence[str],
    selected: Iterable[Sequence[str]],
    *,
    order: int,
    heredity_fraction: float = 0.5,
    max_candidates: int | None = None,
) -> list[Interaction]:
    """Construct the next SIAN-style frontier under fractional heredity.

    Candidates are generated by joining selected terms of order ``order - 1``.
    A candidate survives when at least ``heredity_fraction`` of its immediate
    lower-order subsets have already been selected.
    """
    names = tuple(feature_names)
    if len(set(names)) != len(names):
        raise ValueError("feature_names must be unique.")
    if order < 2:
        raise ValueError("Interaction frontiers start at order 2.")
    if not 0.0 <= heredity_fraction <= 1.0:
        raise ValueError("heredity_fraction must lie in [0, 1].")
    if max_candidates is not None and max_candidates < 1:
        raise ValueError("max_candidates must be positive when provided.")

    position = {name: index for index, name in enumerate(names)}
    selected_set = {
        tuple(sorted(term, key=position.__getitem__)) for term in selected
    }
    previous = sorted(
        (term for term in selected_set if len(term) == order - 1),
        key=lambda term: tuple(position[name] for name in term),
    )

    proposed: set[Interaction] = set()
    if order == 2:
        proposed.update(combinations(names, 2))
    else:
        for left_index, left in enumerate(previous):
            for right in previous[left_index + 1 :]:
                union = tuple(
                    sorted(set(left).union(right), key=position.__getitem__)
                )
                if len(union) == order:
                    proposed.add(union)

    frontier = []
    for candidate in sorted(
        proposed, key=lambda term: tuple(position[name] for name in term)
    ):
        if candidate in selected_set:
            continue
        subsets = immediate_subsets(candidate)
        selected_fraction = sum(
            subset in selected_set for subset in subsets
        ) / len(subsets)
        if selected_fraction >= heredity_fraction:
            frontier.append(candidate)
            if max_candidates is not None and len(frontier) >= max_candidates:
                break
    return frontier


__all__ = ["immediate_subsets", "interaction_frontier"]
