"""Backward-compatible imports for renamed smooth base module."""

from .smooth_base import (
    RUNTIME_TERM_INTERFACE_CHECKLIST,
    BaseSmoothTerm,
    ByState,
    FeatureMatrixState,
    _column_from_matrix,
    _is_effectively_constant,
    _normalize_knots,
    _normalize_mc,
    _normalize_point_constraint,
    _normalize_point_constraint_vector,
    _resolve_feature,
    _resolve_numeric_by,
    apply_numeric_by,
    build_penalty_definition,
    build_selection_penalty_definition,
    by_values_from_new_data,
    column_as_float,
    column_as_object,
    columns_as_float_matrix,
    resolve_by_state,
    resolve_feature_matrix_state,
    sync_by_state_attributes,
    term_penalty_metadata,
)

__all__ = [
    "RUNTIME_TERM_INTERFACE_CHECKLIST",
    "BaseSmoothTerm",
    "ByState",
    "FeatureMatrixState",
    "_column_from_matrix",
    "_is_effectively_constant",
    "_normalize_knots",
    "_normalize_mc",
    "_normalize_point_constraint",
    "_normalize_point_constraint_vector",
    "_resolve_feature",
    "_resolve_numeric_by",
    "apply_numeric_by",
    "build_penalty_definition",
    "build_selection_penalty_definition",
    "by_values_from_new_data",
    "column_as_float",
    "column_as_object",
    "columns_as_float_matrix",
    "resolve_by_state",
    "resolve_feature_matrix_state",
    "sync_by_state_attributes",
    "term_penalty_metadata",
]
